# Wyam build pipeline
# Publishes content produced by Wyam to an Artifact named 'content'
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
    include:
    - master
pr: none

variables:
  - group: blog

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  jobs:
  - job: wyam
    steps:
    - pwsh: dotnet tool install -g Wyam.Tool
      displayName: 'install wyam global tool'

    - pwsh: pwsh -C $env:USERPROFILE\.dotnet\tools\wyam build -o $(Build.ArtifactStagingDirectory)\content
      displayName: 'build site'
    - pwsh: ls -l .
      displayName: 'list cwd'
    - pwsh: ls -l $(Build.ArtifactStagingDirectory)
      displayName: 'list stage'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\content\'
        ArtifactName: 'content'
        publishLocation: 'Container'

- stage: Deploy
  jobs:
  - job: CopyBlob
    steps:
    - download: current
      artifact: content
    - task: AzureFileCopy@3
      displayName: copy
      inputs:
        sourcePath: $(Pipeline.Workspace)/content
        azureSubscription: michael-azure
        destination: azureBlob
        storage: $(StorageAccountName)
        containerName: $(StorageContainer)
        cleanTargetBeforeCopy: true
    - task: AzureCLI@2
      displayName: set-cache-control
      inputs:
        azureSubscription: 'michael-azure'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        powerShellErrorActionPreference: 'continue'
        inlineScript: |
          $containerName = "$web";
          
          # Blob Update Settings
          $contentCacheControl = "max-age=31536000"; # 1 year, lighthouse recommended
          $extensions = @(".gif", ".jpg", ".jpeg", ".ico", ".png", ".css", ".js", ".ttf", ".eot", ".svg", ".woff",".woff2");
          
          # Read all blobs
          $blobs = az storage blob list --auth-mode login --account-name $env:StorageAccountName --container-name $env:StorageContainer --num-results * --output json | ConvertFrom-Json
          
          # Iterate all blobs with .rss extension
          foreach($blob in ($blobs | ? {$_.name -like '*.rss'}))
          {
            # use name as identifier
            $blobName = $blob.name;
            # set content-type to text/xml
            az storage blob update  --auth-mode login --account-name $env:StorageAccountName --container-name $env:StorageContainer --name $blobName --content-type "text/xml"
            Write-Host "Updated $blobName" 
          }
          
          # iterate all blobs with a different cache control setting
          foreach($blob in ($blobs | ? {$_.Properties.contentSettings.cacheControl -notlike $contentCacheControl}))
          {
              # use name as identifier
              $blobName = $blob.name;
          
              # get extension
              $extension = [System.IO.Path]::GetExtension($blobName).ToLower();
           
              # update blob if extension is affected
              if($extensions.Contains($extension))
              {
                  az storage blob update  --auth-mode login --account-name $env:StorageAccountName --container-name $env:StorageContainer --name $blobName --content-cache-control $contentCacheControl
                  Write-Host "Updated $blobName" 
              }
          }
    - task: AzureCLI@2
      displayName: purge front door
      inputs:
        azureSubscription: 'michael-azure'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: 'az extension add --name front-door; az network front-door purge-endpoint --content-paths "/*" --name $env:FrontDoorName --resource-group $env:ResourceGroupName'
              