# Wyam build pipeline
# Publishes content produced by Wyam to an Artifact named 'content'
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  - group: blog

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  jobs:
  - job: wyam
    steps:
    - script: dotnet tool install -g Wyam.Tool
      displayName: 'install wyam global tool'

    - script: $env:USERPROFILE\.dotnet\tools\wyam build -o $(Build.ArtifactStagingDirectory)\content
      displayName: 'build site'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\content\**\*'
        ArtifactName: 'content'
        publishLocation: 'Container'

- stage: Deploy
  jobs:
  - job: CopyBlob
    steps:
    - download: current
      artifact: content
    - task: AzureFileCopy@3
      displayName: copy
      inputs:
        sourcePath: $(Pipeline.Workspace)/content
        azureSubscription: michael-azure
        destination: azureBlob
        storage: $(StorageAccountName)
        containerName: $(StorageContainer)
        cleanTargetBeforeCopy: true