MinimumStatiqWebVersion-CleanBlog: "1.0.0-beta.3"
SiteTitle: Michael Burch's Blog
Author: Michael Burch
Intro: Cloud Enthusiast, Christian, Runner, Blogger
PageTitle: |
  =>
  {
    string siteTitle = Context.GetString("SiteTitle");
    string title = GetString("Title");
    return string.IsNullOrWhiteSpace(siteTitle) ? title : (string.IsNullOrWhiteSpace(title) ? siteTitle : $"{siteTitle} - {title}");
  }
Copyright: => $"Copyright © {DateTime.Now.Year}"
PostSources: blog/*
IsPost: => Outputs.FilterSources(Context.GetString("PostSources")).ContainsById(Document)
Layout: /_postlayout.cshtml