SiteTitle: Michael Burch's Blog
Author: Michael Burch
Description: "Michael Burch is a technologist, cloud enthusiast, programmer, runner, hiker, husband, father and more."
FeedAuthor: me@michaelburch.net
FeedTitle: Michael Burch's Blog
Intro: Cloud Enthusiast, Christian, Runner, Blogger
PageTitle: |
  =>
  {
    string siteTitle = Context.GetString("SiteTitle");
    string title = GetString("Title");
    return string.IsNullOrWhiteSpace(siteTitle) ? title : (string.IsNullOrWhiteSpace(title) ? siteTitle : $"{siteTitle} - {title}");
  }
Copyright: => $"Copyright © {DateTime.Now.Year}"
PostSources: blog/*
IsPost: => Outputs.FilterSources(Context.GetString("PostSources")).ContainsById(Document)
Layout: /_postlayout.cshtml
Host: www.michaelburch.net
LinksUseHttps: true
GenerateCustomSearchIndex: true
AdditionalSearchResultFields: => return new string[] {"Published","Excerpt"};
SearchScriptPath: assets/js/search.js
FeedImageLink: "https://www.michaelburch.net/favicon-32x32.png"
#Image: https://www.michaelburch.net/images/logo.svg
#LinkLowercase: false
#OptimizeContentFileNames: false